export const videos = [
  {
    id: "1",
    src: "video/1.MP4",
    author: "nature.daily",
    title: "Morning bloom",
    caption: "Демонстрационный ролик. Активный слайд воспроизводится, остальные ставятся на паузу для экономии ресурсов.",
    likes: 1820,
    comments: 64,
  },
  {
    id: "v2",
    src: "video/2.MP4",
    author: "demo.motion",
    title: "Some cool video",
    caption: "Лента реализована на vanilla JavaScript с vertical snap-scroll и IntersectionObserver.",
    likes: 913,
    comments: 27,
  },
  {
    id: "v3",
    src: "video/3.MP4",
    author: "cinema.test",
    title: "Trailer cut",
    caption: "Есть поддержка mobile и desktop, клавиатурная навигация и минимальный адаптивный UI.",
    likes: 2401,
    comments: 111,
  },
  {
    id: "v4",
    src: "video/4.MP4",
    author: "cinema.test",
    title: "Lorem ipsum",
    caption: "И тут вдохновение кончилось.",
    likes: 2401,
    comments: 111,
  },
  {
    id: "v5",
    src: "video/5.MP4",
    author: "cinema.test",
    title: "Lorem ipsum",
    caption: "Но инженер останавливается не когда устал, когда закончил задачу",
    likes: 2401,
    comments: 111,
  },
  {
    id: "v6",
    src: "video/6.MP4",
    author: "cinema.test",
    title: "Bang bang...",
    caption: "Поэтому продожаем без вдохновения",
    likes: 2401,
    comments: 111,
  },
  {
    id: "v7",
    src: "video/7.MP4",
    author: "cinema.test",
    title: "Awesome title",
    caption: "Поэтому продожаем без вдохновения",
    likes: 2401,
    comments: 111,
  },
  {
    id: "v8",
    src: "video/8.MP4",
    author: "cinema.test",
    title: "JAAT",
    caption: "Продолжаем продолжаем продолжаем",
    likes: 2401,
    comments: 111,
  },
  {
    id: "v9",
    src: "video/9.MP4",
    author: "cinema.test",
    title: "JAAT",
    caption: "без вдохновения без вдоновения без вдохновения",
    likes: 2401,
    comments: 111,
  },
  {
    id: "v10",
    src: "video/10.MP4",
    author: "cinema.test",
    title: "JAAT",
    caption: "Я устал я ухожу",
    likes: 2401,
    comments: 111,
  },
];
